/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.presupuesto.vista;

import com.presupuesto.control.AccesoDatos;
import com.presupuesto.modelo.Vigencia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Luis Fernando Leiva
 */
public class Administracion_Vigencias extends javax.swing.JInternalFrame {

    AccesoDatos accesoDatos;
    Home home;

    /**
     * Creates new form Administracion_Vigencias
     */
    public Administracion_Vigencias(Home parent) {
        super();
        this.home = parent;

        initComponents();

        // Elimina el la decoracion en la ventana interna
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);

        consultarVigencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraHerramientas = new javax.swing.JToolBar();
        nuevaVigencia = new javax.swing.JLabel();
        guardarRegistro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        eliminarRegistro = new javax.swing.JLabel();
        labelVigencia = new javax.swing.JLabel();
        frListaVigencias = new javax.swing.JComboBox<>();
        barraMenu = new javax.swing.JMenuBar();
        menuAdicion = new javax.swing.JMenu();
        itemNuevo = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        itemEliminar = new javax.swing.JMenuItem();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(895, 474));
        setMinimumSize(new java.awt.Dimension(895, 474));
        setPreferredSize(new java.awt.Dimension(895, 474));

        barraHerramientas.setBackground(new java.awt.Color(255, 255, 255));
        barraHerramientas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        nuevaVigencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevaVigencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/Nueva_Vigencia.png"))); // NOI18N
        nuevaVigencia.setToolTipText("Nueva Vigencia");
        nuevaVigencia.setAlignmentX(0.5F);
        nuevaVigencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nuevaVigencia.setMaximumSize(new java.awt.Dimension(25, 20));
        nuevaVigencia.setMinimumSize(new java.awt.Dimension(25, 20));
        nuevaVigencia.setPreferredSize(new java.awt.Dimension(25, 20));
        nuevaVigencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevaVigenciaMousePressed(evt);
            }
        });
        barraHerramientas.add(nuevaVigencia);

        guardarRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/guardar.png"))); // NOI18N
        guardarRegistro.setAlignmentX(0.5F);
        guardarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        guardarRegistro.setMaximumSize(new java.awt.Dimension(25, 20));
        guardarRegistro.setMinimumSize(new java.awt.Dimension(25, 20));
        guardarRegistro.setPreferredSize(new java.awt.Dimension(25, 20));
        guardarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarRegistroMousePressed(evt);
            }
        });
        barraHerramientas.add(guardarRegistro);
        barraHerramientas.add(jSeparator1);

        eliminarRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/eliminar.png"))); // NOI18N
        eliminarRegistro.setAlignmentX(0.5F);
        eliminarRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eliminarRegistro.setMaximumSize(new java.awt.Dimension(25, 20));
        eliminarRegistro.setMinimumSize(new java.awt.Dimension(25, 20));
        eliminarRegistro.setPreferredSize(new java.awt.Dimension(25, 20));
        eliminarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarRegistroMousePressed(evt);
            }
        });
        barraHerramientas.add(eliminarRegistro);

        labelVigencia.setText("Vigencia Activa");

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));

        menuAdicion.setText("Vigencia");

        itemNuevo.setText("Nueva Vigencia");
        itemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoActionPerformed(evt);
            }
        });
        menuAdicion.add(itemNuevo);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        menuAdicion.add(itemGuardar);

        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuAdicion.add(itemCerrar);

        barraMenu.add(menuAdicion);

        menuEditar.setText("Editar");

        itemEliminar.setText("Eliminar");
        itemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarActionPerformed(evt);
            }
        });
        menuEditar.add(itemEliminar);

        barraMenu.add(menuEditar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(labelVigencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frListaVigencias, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(529, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVigencia)
                    .addComponent(frListaVigencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 350, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void consultarVigencias() {
        frListaVigencias.removeAllItems();
        accesoDatos = new AccesoDatos();
        List<Vigencia> listaVigencia = new ArrayList<Vigencia>();

        listaVigencia = accesoDatos.consultarTodos(new Vigencia(), Vigencia.class);

        if (!listaVigencia.isEmpty()) {            
            for (Vigencia vigencia : listaVigencia) {
                if (vigencia.getActiva()) {
                    frListaVigencias.addItem(vigencia.getVigencia() + " (Activa)");
                    frListaVigencias.setSelectedItem(vigencia.getVigencia() + " (Activa)");                      
                } else {
                    frListaVigencias.addItem(vigencia.getVigencia());
                }
            }            
        }
    }

    private void itemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoActionPerformed
        Crear_Vigencia crear_Vigencia = new Crear_Vigencia(this, true);
        crear_Vigencia.setLocationRelativeTo(null);
        crear_Vigencia.setVisible(true);
    }//GEN-LAST:event_itemNuevoActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed

    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        home.getVentanaPrincipal().remove(this);
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarActionPerformed

    }//GEN-LAST:event_itemEliminarActionPerformed

    private void guardarRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarRegistroMousePressed
        accesoDatos = new AccesoDatos();
        String vigenciaSeleccionada = frListaVigencias.getSelectedItem().toString();
        int validar = vigenciaSeleccionada.indexOf("Activa");

        if (validar > 0) {
            vigenciaSeleccionada = vigenciaSeleccionada.substring(0, validar - 2).trim();
        } else {
            vigenciaSeleccionada = vigenciaSeleccionada.trim();
        }

        List<Vigencia> listaVigencias = new ArrayList<Vigencia>();
        Vigencia vigencia = new Vigencia();
        vigencia.setVigencia(vigenciaSeleccionada);

        vigencia = accesoDatos.consultarTodos(vigencia, Vigencia.class).get(0);

        if (!vigencia.getActiva()) {
            listaVigencias = accesoDatos.consultarTodos(new Vigencia(), Vigencia.class);

            for (Vigencia vigenciaIterada : listaVigencias) {
                if (vigencia.getIdVigencia().equals(vigenciaIterada.getIdVigencia())) {
                    vigencia.setActiva(true);
                    vigencia = accesoDatos.persistirActualizar(vigencia);
                } else {
                    vigenciaIterada.setActiva(false);
                    accesoDatos.persistirActualizar(vigenciaIterada);
                }
            }
        }

        listaVigencias = accesoDatos.consultarTodos(new Vigencia(), Vigencia.class);

        if (!listaVigencias.isEmpty()) {

            frListaVigencias.removeAllItems();

            for (Vigencia vigenciaIterada : listaVigencias) {
                if (vigenciaIterada.getActiva()) {
                    frListaVigencias.addItem(vigenciaIterada.getVigencia() + " (Activa)");
                    frListaVigencias.setSelectedItem(vigenciaIterada.getVigencia() + " (Activa)");      
                    home.vigenciaActiva(vigencia);
                } else {
                    frListaVigencias.addItem(vigenciaIterada.getVigencia());
                }
            }
            
            
        }
    }//GEN-LAST:event_guardarRegistroMousePressed

    private void eliminarRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarRegistroMousePressed

    }//GEN-LAST:event_eliminarRegistroMousePressed

    private void nuevaVigenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaVigenciaMousePressed
        Crear_Vigencia crear_Vigencia = new Crear_Vigencia(this, true);
        crear_Vigencia.setLocationRelativeTo(null);
        crear_Vigencia.setVisible(true);
    }//GEN-LAST:event_nuevaVigenciaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JLabel eliminarRegistro;
    private javax.swing.JComboBox<String> frListaVigencias;
    private javax.swing.JLabel guardarRegistro;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemEliminar;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemNuevo;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JLabel labelVigencia;
    private javax.swing.JMenu menuAdicion;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JLabel nuevaVigencia;
    // End of variables declaration//GEN-END:variables
}
