/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.presupuesto.vista;

import com.presupuesto.control.AccesoDatos;
import com.presupuesto.modelo.Entidad;
import com.presupuesto.modelo.Vigencia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author fleiva
 */
public class Home extends javax.swing.JFrame {

    // ***** Atributos de la clase *****//
    AccesoDatos accesoDatos;
    Vigencia vigencia;
    boolean loginExitoso;

    /**
     * Creates new form Home
     */
    public Home() {
        boolean existeVigencia = false;
        boolean existeRegistroEntidad = false;
        loginExitoso = false;

        initComponents();

        // Icono
        setIconImage(new ImageIcon(getClass().getResource("/com/presupuesto/img/Icono.png")).getImage());
        // Posicion centro de pantalla
        this.setLocationRelativeTo(null);
        // Se quita decoracion de pantalla al frame interno
        ((BasicInternalFrameUI) infoEmpresa.getUI()).setNorthPane(null);
        infoEmpresa.setBorder(null);

        Login_Dialog login = new Login_Dialog(this, true);
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        if (loginExitoso) {
            existeVigencia = consultarVigencia();
            existeRegistroEntidad = cargarInformacionEntidad();

            if (!existeVigencia) {
                registrarPrimeraVigencia();
            } else if (existeRegistroEntidad) {
                cargarInformacionEntidad();
                this.setVisible(true);
            } else {
                //
            }
        }
    }

    /**
     * Metodo para consultar vigencia actual
     */
    private boolean consultarVigencia() {
        boolean existenVigencias = true;
        accesoDatos = new AccesoDatos();
        vigencia = new Vigencia();
        vigencia.setActiva(true);
        List<Vigencia> listaVigencias = new ArrayList<Vigencia>();
        listaVigencias = accesoDatos.consultarTodos(vigencia, Vigencia.class);

        if (!listaVigencias.isEmpty()) {
            vigencia = listaVigencias.get(0);
        } else {
            existenVigencias = false;
        }

        return existenVigencias;
    }

    public Vigencia getVigencia() {
        return vigencia;
    }

    public void registrarPrimeraVigencia() {
        CrearVigenciaInicial nuevaVigencia = new CrearVigenciaInicial(this, true);
        nuevaVigencia.setLocationRelativeTo(null);
        nuevaVigencia.setVisible(true);
    }
    
    public void registroInicialEntidad() {
        RegistroInicialEntidad registroEntidad = new RegistroInicialEntidad(this, true);
        registroEntidad.setLocationRelativeTo(null);
        registroEntidad.setVisible(true);
    }

    private boolean cargarInformacionEntidad() {
        accesoDatos = new AccesoDatos();
        Entidad entidad = new Entidad();
        List<Entidad> listaEntidad = new ArrayList<Entidad>();        
        listaEntidad = accesoDatos.consultarTodos(entidad, Entidad.class);
        
        if (!listaEntidad.isEmpty()) {
            entidad = listaEntidad.get(0);
            datosEntidad(entidad);
            return true;
        } else {
            return false;
        }                       
    }

    // ***** Metodos Privados ***** //    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JTabbedPane();
        infoEmpresa = new javax.swing.JInternalFrame();
        panelInformacionEntidad = new javax.swing.JPanel();
        nombreEntidad = new javax.swing.JLabel();
        nitEntidad = new javax.swing.JLabel();
        departamentoCiudad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        accesoDisponibilidad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accesoRegistro = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accesoOrdenPrestacionServicios = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        accesoOrdenSuministro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accesoComprobante = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        accesoEjecucion = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuPresupuesto = new javax.swing.JMenu();
        itemRubros = new javax.swing.JMenuItem();
        itemPresupuestoInicial = new javax.swing.JMenuItem();
        itemAdicionPresupuestal = new javax.swing.JMenuItem();
        itemTrasladoPresupuestal = new javax.swing.JMenuItem();
        itemEjecucionPrespuestal = new javax.swing.JMenuItem();
        itemVigenciaPresupuestal = new javax.swing.JMenuItem();
        menuEgresos = new javax.swing.JMenu();
        itemBeneficiario = new javax.swing.JMenuItem();
        itemDisponibilidadPrespuestal = new javax.swing.JMenuItem();
        itemRegistroPrespuestal = new javax.swing.JMenuItem();
        itemOrdenPrestacionServicio = new javax.swing.JMenuItem();
        itemOrdenSuministro = new javax.swing.JMenuItem();
        itemComprobanteEgreso = new javax.swing.JMenuItem();
        menuAdministrar = new javax.swing.JMenu();
        itemBaseDeDatos = new javax.swing.JMenu();
        itemExportarDB = new javax.swing.JMenuItem();
        itemImportarDB = new javax.swing.JMenuItem();
        itemInformacionEntidad = new javax.swing.JMenuItem();
        itemCambioContraseña = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemManual = new javax.swing.JMenuItem();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presupuesto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        infoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        infoEmpresa.setMaximumSize(new java.awt.Dimension(895, 474));
        infoEmpresa.setMinimumSize(new java.awt.Dimension(895, 474));
        infoEmpresa.setVisible(true);

        panelInformacionEntidad.setBackground(new java.awt.Color(97, 99, 115));
        panelInformacionEntidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelInformacionEntidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEntidad.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        nombreEntidad.setForeground(new java.awt.Color(255, 255, 255));
        nombreEntidad.setAlignmentY(0.0F);
        panelInformacionEntidad.add(nombreEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 400, 30));

        nitEntidad.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        nitEntidad.setForeground(new java.awt.Color(255, 255, 255));
        nitEntidad.setAlignmentY(0.0F);
        panelInformacionEntidad.add(nitEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 35, 340, 20));

        departamentoCiudad.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        departamentoCiudad.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionEntidad.add(departamentoCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 55, 340, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/AccesoHome.png"))); // NOI18N

        accesoDisponibilidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accesoDisponibilidad.setForeground(new java.awt.Color(0, 51, 102));
        accesoDisponibilidad.setText("Disponibilidad Presupuestal");
        accesoDisponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accesoDisponibilidadMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/AccesoHome.png"))); // NOI18N

        accesoRegistro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accesoRegistro.setForeground(new java.awt.Color(0, 51, 102));
        accesoRegistro.setText("Registro Presupuestal");
        accesoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accesoRegistroMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/AccesoHome.png"))); // NOI18N

        accesoOrdenPrestacionServicios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accesoOrdenPrestacionServicios.setForeground(new java.awt.Color(0, 51, 102));
        accesoOrdenPrestacionServicios.setText("Orden de Prestación de Servicios");
        accesoOrdenPrestacionServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoOrdenPrestacionServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accesoOrdenPrestacionServiciosMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/AccesoHome.png"))); // NOI18N

        accesoOrdenSuministro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accesoOrdenSuministro.setForeground(new java.awt.Color(0, 51, 102));
        accesoOrdenSuministro.setText("Orden de Suministro");
        accesoOrdenSuministro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoOrdenSuministro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accesoOrdenSuministroMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/AccesoHome.png"))); // NOI18N

        accesoComprobante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accesoComprobante.setForeground(new java.awt.Color(0, 51, 102));
        accesoComprobante.setText("Comprobante de Egreso");
        accesoComprobante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoComprobante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accesoComprobanteMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/AccesoHome.png"))); // NOI18N

        accesoEjecucion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accesoEjecucion.setForeground(new java.awt.Color(0, 51, 102));
        accesoEjecucion.setText("Ejecución Presupuestal");
        accesoEjecucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoEjecucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accesoEjecucionMousePressed(evt);
            }
        });

        barraMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        menuPresupuesto.setText("Presupuesto");

        itemRubros.setText("Rubros Presupuestales");
        itemRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRubrosActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemRubros);

        itemPresupuestoInicial.setText("Presupuesto Inicial");
        itemPresupuestoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPresupuestoInicialActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemPresupuestoInicial);

        itemAdicionPresupuestal.setText("Adicion Presupuestal");
        itemAdicionPresupuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdicionPresupuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemAdicionPresupuestal);

        itemTrasladoPresupuestal.setText("Traslado Presupuestal");
        itemTrasladoPresupuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTrasladoPresupuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemTrasladoPresupuestal);

        itemEjecucionPrespuestal.setText("Ejecucion Presupuestal");
        itemEjecucionPrespuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEjecucionPrespuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemEjecucionPrespuestal);

        itemVigenciaPresupuestal.setText("Vigencia Presupuestal");
        itemVigenciaPresupuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVigenciaPresupuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemVigenciaPresupuestal);

        barraMenuPrincipal.add(menuPresupuesto);

        menuEgresos.setText("Egresos");

        itemBeneficiario.setText("Registro Beneficiario");
        itemBeneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBeneficiarioActionPerformed(evt);
            }
        });
        menuEgresos.add(itemBeneficiario);

        itemDisponibilidadPrespuestal.setText("Disponibilidad Prespuestal");
        itemDisponibilidadPrespuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDisponibilidadPrespuestalActionPerformed(evt);
            }
        });
        menuEgresos.add(itemDisponibilidadPrespuestal);

        itemRegistroPrespuestal.setText("Registro Prespuestal");
        itemRegistroPrespuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroPrespuestalActionPerformed(evt);
            }
        });
        menuEgresos.add(itemRegistroPrespuestal);

        itemOrdenPrestacionServicio.setText("Orden de Prestacion de Servicios");
        itemOrdenPrestacionServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrdenPrestacionServicioActionPerformed(evt);
            }
        });
        menuEgresos.add(itemOrdenPrestacionServicio);

        itemOrdenSuministro.setText("Orden de Suministro");
        itemOrdenSuministro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrdenSuministroActionPerformed(evt);
            }
        });
        menuEgresos.add(itemOrdenSuministro);

        itemComprobanteEgreso.setText("Comprobante de Egreso");
        itemComprobanteEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComprobanteEgresoActionPerformed(evt);
            }
        });
        menuEgresos.add(itemComprobanteEgreso);

        barraMenuPrincipal.add(menuEgresos);

        menuAdministrar.setText("Administrar");

        itemBaseDeDatos.setText("Base de Datos");

        itemExportarDB.setText("Exportar Backup");
        itemExportarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExportarDBActionPerformed(evt);
            }
        });
        itemBaseDeDatos.add(itemExportarDB);

        itemImportarDB.setText("Importar Backup");
        itemImportarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemImportarDBActionPerformed(evt);
            }
        });
        itemBaseDeDatos.add(itemImportarDB);

        menuAdministrar.add(itemBaseDeDatos);

        itemInformacionEntidad.setText("Informacion Entidad");
        itemInformacionEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionEntidadActionPerformed(evt);
            }
        });
        menuAdministrar.add(itemInformacionEntidad);

        itemCambioContraseña.setText("Cambio Contraseña");
        itemCambioContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCambioContraseñaActionPerformed(evt);
            }
        });
        menuAdministrar.add(itemCambioContraseña);

        barraMenuPrincipal.add(menuAdministrar);

        menuAyuda.setText("Ayuda");

        itemManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        itemManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/Pdf.png"))); // NOI18N
        itemManual.setText("Manual");
        itemManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManualActionPerformed(evt);
            }
        });
        menuAyuda.add(itemManual);

        itemAcercaDe.setText("Acerca de");
        itemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcercaDe);

        barraMenuPrincipal.add(menuAyuda);

        infoEmpresa.setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout infoEmpresaLayout = new javax.swing.GroupLayout(infoEmpresa.getContentPane());
        infoEmpresa.getContentPane().setLayout(infoEmpresaLayout);
        infoEmpresaLayout.setHorizontalGroup(
            infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacionEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEmpresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesoOrdenSuministro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesoOrdenPrestacionServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accesoDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        infoEmpresaLayout.setVerticalGroup(
            infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(accesoDisponibilidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(accesoRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(accesoOrdenPrestacionServicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(accesoOrdenSuministro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(accesoComprobante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(accesoEjecucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(panelInformacionEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ventanaPrincipal.addTab("", new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/Home.png")), infoEmpresa, ""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRubrosActionPerformed
        Rubro_Presupuestal rubroPresupuestal = new Rubro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Rubro Presupuestal", rubroPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemRubrosActionPerformed

    private void itemPresupuestoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPresupuestoInicialActionPerformed
        Presupuesto_Inicial presupuesto = new Presupuesto_Inicial(this);
        this.ventanaPrincipal.addTab("Presupuesto", presupuesto);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemPresupuestoInicialActionPerformed

    private void itemAdicionPresupuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdicionPresupuestalActionPerformed
        Adicion_Presupuestal adicion = new Adicion_Presupuestal(this);
        this.ventanaPrincipal.addTab("Adicion Presupuestal", adicion);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemAdicionPresupuestalActionPerformed

    private void itemBeneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBeneficiarioActionPerformed
        Beneficiario_Presupuesto beneficiarioPresupuesto = new Beneficiario_Presupuesto(this);
        this.ventanaPrincipal.addTab("Beneficiario", beneficiarioPresupuesto);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemBeneficiarioActionPerformed

    private void itemDisponibilidadPrespuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDisponibilidadPrespuestalActionPerformed
        Disponibilidad_Presupuestal disponibilidadPresupuestal = new Disponibilidad_Presupuestal(this);
        this.ventanaPrincipal.addTab("Disponibilidad Presupuestal", disponibilidadPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemDisponibilidadPrespuestalActionPerformed

    private void itemEjecucionPrespuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEjecucionPrespuestalActionPerformed
        Ejecucion_Presupuestal ejecucionPresupuestal = new Ejecucion_Presupuestal(this);
        this.ventanaPrincipal.addTab("Ejecución Presupuestal", ejecucionPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemEjecucionPrespuestalActionPerformed

    private void itemTrasladoPresupuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTrasladoPresupuestalActionPerformed
        Traslado_Presupuestal trasladoPresupuestal = new Traslado_Presupuestal(this);
        this.ventanaPrincipal.addTab("Traslado Presupuestal", trasladoPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemTrasladoPresupuestalActionPerformed

    private void itemRegistroPrespuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroPrespuestalActionPerformed
        Registro_Presupuestal registroPresupuestal = new Registro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Registro Presupuestal", registroPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemRegistroPrespuestalActionPerformed

    private void itemOrdenPrestacionServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrdenPrestacionServicioActionPerformed
        Orden_Prestacion_Servicio_Presupuestal ops = new Orden_Prestacion_Servicio_Presupuestal(this);
        this.ventanaPrincipal.addTab("Orden de Prestacion de Servicio", ops);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemOrdenPrestacionServicioActionPerformed

    private void itemComprobanteEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComprobanteEgresoActionPerformed
        Comprobante_Egreso comprobante = new Comprobante_Egreso(this);
        this.ventanaPrincipal.addTab("Comrpobante de Egreso", comprobante);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemComprobanteEgresoActionPerformed

    private void itemOrdenSuministroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrdenSuministroActionPerformed
        Orden_Suministro_Presupuestal orden = new Orden_Suministro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Orden de Suministro", orden);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemOrdenSuministroActionPerformed

    private void itemImportarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemImportarDBActionPerformed
        RestaurarBD restaurar = new RestaurarBD(this, true);
        restaurar.setLocationRelativeTo(null);
        restaurar.setVisible(true);
    }//GEN-LAST:event_itemImportarDBActionPerformed

    private void itemExportarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExportarDBActionPerformed
        Backup_BD backup = new Backup_BD(this, true);
        backup.setLocationRelativeTo(null);
        backup.setVisible(true);
    }//GEN-LAST:event_itemExportarDBActionPerformed

    private void itemInformacionEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionEntidadActionPerformed
        Informacion_Entidad entidad = new Informacion_Entidad(this);
        this.ventanaPrincipal.addTab("Informacion de Entidad", entidad);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemInformacionEntidadActionPerformed

    private void itemCambioContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCambioContraseñaActionPerformed
        Cambio_Contrasena pass = new Cambio_Contrasena(this, true);
        pass.setLocationRelativeTo(null);
        pass.setVisible(true);
    }//GEN-LAST:event_itemCambioContraseñaActionPerformed

    private void itemVigenciaPresupuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVigenciaPresupuestalActionPerformed
        Administracion_Vigencias admVigencia = new Administracion_Vigencias(this);
        this.ventanaPrincipal.addTab("Administración Vigencias", admVigencia);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemVigenciaPresupuestalActionPerformed

    private void accesoDisponibilidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoDisponibilidadMousePressed
        Disponibilidad_Presupuestal disponibilidadPresupuestal = new Disponibilidad_Presupuestal(this);
        this.ventanaPrincipal.addTab("Disponibilidad Presupuestal", disponibilidadPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_accesoDisponibilidadMousePressed

    private void accesoRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoRegistroMousePressed
        Registro_Presupuestal registroPresupuestal = new Registro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Registro Presupuestal", registroPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_accesoRegistroMousePressed

    private void accesoOrdenPrestacionServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoOrdenPrestacionServiciosMousePressed
        Orden_Prestacion_Servicio_Presupuestal ops = new Orden_Prestacion_Servicio_Presupuestal(this);
        this.ventanaPrincipal.addTab("Orden de Prestacion de Servicio", ops);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_accesoOrdenPrestacionServiciosMousePressed

    private void accesoOrdenSuministroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoOrdenSuministroMousePressed
        Orden_Suministro_Presupuestal orden = new Orden_Suministro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Orden de Suministro", orden);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_accesoOrdenSuministroMousePressed

    private void accesoComprobanteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoComprobanteMousePressed
        Comprobante_Egreso comprobante = new Comprobante_Egreso(this);
        this.ventanaPrincipal.addTab("Comrpobante de Egreso", comprobante);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_accesoComprobanteMousePressed

    private void accesoEjecucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoEjecucionMousePressed
        Ejecucion_Presupuestal ejecucionPresupuestal = new Ejecucion_Presupuestal(this);
        this.ventanaPrincipal.addTab("Ejecución Presupuestal", ejecucionPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_accesoEjecucionMousePressed

    private void itemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcercaDeActionPerformed
        // Abrir Acerca de
        AcercaDe acercaDe = new AcercaDe(this, true);
        acercaDe.setLocationRelativeTo(null);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_itemAcercaDeActionPerformed

    private void itemManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManualActionPerformed
        System.out.println("Abrir Manual");
    }//GEN-LAST:event_itemManualActionPerformed

    //***** Metodos Publicos *****//
    public void datosEntidad(Entidad entidad) {
        nombreEntidad.setText(entidad.getNombre());
        nitEntidad.setText("Nit. " + entidad.getNit());
        departamentoCiudad.setText(entidad.getCiudad() + " - " + entidad.getDepartamento());
        this.setTitle("Presupuesto - " + entidad.getNombreCorto() + " - Vigencia " + vigencia.getVigencia());
    }

    public void vigenciaActiva(Vigencia vigencia) {
        String tituloHome = this.getTitle();
        String titulo = tituloHome.substring(0, tituloHome.indexOf("Vigencia"));
        this.setTitle(titulo + "Vigencia " + vigencia.getVigencia());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    //***** Getters & Setters *****//
    public JTabbedPane getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(JTabbedPane ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }

    public boolean isLoginExitoso() {
        return loginExitoso;
    }

    public void setLoginExitoso(boolean loginExitoso) {
        this.loginExitoso = loginExitoso;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accesoComprobante;
    private javax.swing.JLabel accesoDisponibilidad;
    private javax.swing.JLabel accesoEjecucion;
    private javax.swing.JLabel accesoOrdenPrestacionServicios;
    private javax.swing.JLabel accesoOrdenSuministro;
    private javax.swing.JLabel accesoRegistro;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JLabel departamentoCiudad;
    private javax.swing.JInternalFrame infoEmpresa;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemAdicionPresupuestal;
    private javax.swing.JMenu itemBaseDeDatos;
    private javax.swing.JMenuItem itemBeneficiario;
    private javax.swing.JMenuItem itemCambioContraseña;
    private javax.swing.JMenuItem itemComprobanteEgreso;
    private javax.swing.JMenuItem itemDisponibilidadPrespuestal;
    private javax.swing.JMenuItem itemEjecucionPrespuestal;
    private javax.swing.JMenuItem itemExportarDB;
    private javax.swing.JMenuItem itemImportarDB;
    private javax.swing.JMenuItem itemInformacionEntidad;
    private javax.swing.JMenuItem itemManual;
    private javax.swing.JMenuItem itemOrdenPrestacionServicio;
    private javax.swing.JMenuItem itemOrdenSuministro;
    private javax.swing.JMenuItem itemPresupuestoInicial;
    private javax.swing.JMenuItem itemRegistroPrespuestal;
    private javax.swing.JMenuItem itemRubros;
    private javax.swing.JMenuItem itemTrasladoPresupuestal;
    private javax.swing.JMenuItem itemVigenciaPresupuestal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu menuAdministrar;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEgresos;
    private javax.swing.JMenu menuPresupuesto;
    private javax.swing.JLabel nitEntidad;
    private javax.swing.JLabel nombreEntidad;
    private javax.swing.JPanel panelInformacionEntidad;
    private javax.swing.JTabbedPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
