/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.presupuesto.vista;

import com.presupuesto.control.AccesoDatos;
import com.presupuesto.modelo.Beneficiario;
import com.presupuesto.modelo.Entidad;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author fleiva
 */
public class Home extends javax.swing.JFrame {

    // ***** Atributos de la clase *****//
    AccesoDatos accesoDatos;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        // Icono
        setIconImage(new ImageIcon(getClass().getResource("/com/presupuesto/img/Icono.png")).getImage());
        // Posicion centro de pantalla
        this.setLocationRelativeTo(null);
        // Se quita decoracion de pantalla al frame interno
        ((BasicInternalFrameUI) infoEmpresa.getUI()).setNorthPane(null);
        infoEmpresa.setBorder(null);
     
        datosEntidad();               
    }
    
    // ***** Metodos Privados ***** //
    private void datosEntidad() {
        accesoDatos = new AccesoDatos();
        Entidad entidad = new Entidad();
        entidad = accesoDatos.consultarTodos(entidad, Entidad.class).get(0);
        nombreEntidad.setText(entidad.getNombre());
        nitEntidad.setText("Nit. " + entidad.getNit());
        departamentoCiudad.setText(entidad.getCiudad() + " - " + entidad.getDepartamento());
        this.setTitle("Presupuesto - " + entidad.getNombreCorto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JTabbedPane();
        infoEmpresa = new javax.swing.JInternalFrame();
        panelInformacionEntidad = new javax.swing.JPanel();
        nombreEntidad = new javax.swing.JLabel();
        nitEntidad = new javax.swing.JLabel();
        departamentoCiudad = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        menuPresupuesto = new javax.swing.JMenu();
        itemRubros = new javax.swing.JMenuItem();
        itemPresupuestoInicial = new javax.swing.JMenuItem();
        itemAdicionPresupuestal = new javax.swing.JMenuItem();
        itemTrasladoPresupuestal = new javax.swing.JMenuItem();
        itemEjecucionPrespuestal = new javax.swing.JMenuItem();
        menuEgresos = new javax.swing.JMenu();
        itemBeneficiario = new javax.swing.JMenuItem();
        itemDisponibilidadPrespuestal = new javax.swing.JMenuItem();
        itemRegistroPrespuestal = new javax.swing.JMenuItem();
        itemOrdenPrestacionServicio = new javax.swing.JMenuItem();
        itemOrdenSuministro = new javax.swing.JMenuItem();
        itemComprobanteEgreso = new javax.swing.JMenuItem();
        menuAdministrar = new javax.swing.JMenu();
        itemBaseDeDatos = new javax.swing.JMenu();
        itemExportarDB = new javax.swing.JMenuItem();
        itemImportarDB = new javax.swing.JMenuItem();
        itemInformacionEntidad = new javax.swing.JMenuItem();
        itemCambioContraseña = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presupuesto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        infoEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        infoEmpresa.setMaximumSize(new java.awt.Dimension(895, 474));
        infoEmpresa.setMinimumSize(new java.awt.Dimension(895, 474));
        infoEmpresa.setVisible(true);

        panelInformacionEntidad.setBackground(new java.awt.Color(97, 99, 115));
        panelInformacionEntidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelInformacionEntidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreEntidad.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        nombreEntidad.setForeground(new java.awt.Color(255, 255, 255));
        nombreEntidad.setAlignmentY(0.0F);
        panelInformacionEntidad.add(nombreEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 400, 30));

        nitEntidad.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        nitEntidad.setForeground(new java.awt.Color(255, 255, 255));
        nitEntidad.setAlignmentY(0.0F);
        panelInformacionEntidad.add(nitEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 35, 340, 20));

        departamentoCiudad.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        departamentoCiudad.setForeground(new java.awt.Color(255, 255, 255));
        panelInformacionEntidad.add(departamentoCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 55, 340, 20));

        barraMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        menuPresupuesto.setText("Presupuesto");

        itemRubros.setText("Rubros Presupuestales");
        itemRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRubrosActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemRubros);

        itemPresupuestoInicial.setText("Presupuesto Inicial");
        itemPresupuestoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPresupuestoInicialActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemPresupuestoInicial);

        itemAdicionPresupuestal.setText("Adicion Presupuestal");
        itemAdicionPresupuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdicionPresupuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemAdicionPresupuestal);

        itemTrasladoPresupuestal.setText("Traslado Presupuestal");
        itemTrasladoPresupuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTrasladoPresupuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemTrasladoPresupuestal);

        itemEjecucionPrespuestal.setText("Ejecucion Presupuestal");
        itemEjecucionPrespuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEjecucionPrespuestalActionPerformed(evt);
            }
        });
        menuPresupuesto.add(itemEjecucionPrespuestal);

        barraMenuPrincipal.add(menuPresupuesto);

        menuEgresos.setText("Egresos");

        itemBeneficiario.setText("Registro Beneficiario");
        itemBeneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBeneficiarioActionPerformed(evt);
            }
        });
        menuEgresos.add(itemBeneficiario);

        itemDisponibilidadPrespuestal.setText("Disponibilidad Prespuestal");
        itemDisponibilidadPrespuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDisponibilidadPrespuestalActionPerformed(evt);
            }
        });
        menuEgresos.add(itemDisponibilidadPrespuestal);

        itemRegistroPrespuestal.setText("Registro Prespuestal");
        itemRegistroPrespuestal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroPrespuestalActionPerformed(evt);
            }
        });
        menuEgresos.add(itemRegistroPrespuestal);

        itemOrdenPrestacionServicio.setText("Orden de Prestacion de Servicios");
        itemOrdenPrestacionServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrdenPrestacionServicioActionPerformed(evt);
            }
        });
        menuEgresos.add(itemOrdenPrestacionServicio);

        itemOrdenSuministro.setText("Orden de Suministro");
        itemOrdenSuministro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrdenSuministroActionPerformed(evt);
            }
        });
        menuEgresos.add(itemOrdenSuministro);

        itemComprobanteEgreso.setText("Comprobante de Egreso");
        itemComprobanteEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComprobanteEgresoActionPerformed(evt);
            }
        });
        menuEgresos.add(itemComprobanteEgreso);

        barraMenuPrincipal.add(menuEgresos);

        menuAdministrar.setText("Administrar");

        itemBaseDeDatos.setText("Base de Datos");

        itemExportarDB.setText("Exportar Backup");
        itemExportarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExportarDBActionPerformed(evt);
            }
        });
        itemBaseDeDatos.add(itemExportarDB);

        itemImportarDB.setText("Importar Backup");
        itemImportarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemImportarDBActionPerformed(evt);
            }
        });
        itemBaseDeDatos.add(itemImportarDB);

        menuAdministrar.add(itemBaseDeDatos);

        itemInformacionEntidad.setText("Informacion Entidad");
        itemInformacionEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionEntidadActionPerformed(evt);
            }
        });
        menuAdministrar.add(itemInformacionEntidad);

        itemCambioContraseña.setText("Cambio Contraseña");
        itemCambioContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCambioContraseñaActionPerformed(evt);
            }
        });
        menuAdministrar.add(itemCambioContraseña);

        barraMenuPrincipal.add(menuAdministrar);

        menuAyuda.setText("Ayuda");

        itemAcercaDe.setText("Acerca de");
        menuAyuda.add(itemAcercaDe);

        barraMenuPrincipal.add(menuAyuda);

        infoEmpresa.setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout infoEmpresaLayout = new javax.swing.GroupLayout(infoEmpresa.getContentPane());
        infoEmpresa.getContentPane().setLayout(infoEmpresaLayout);
        infoEmpresaLayout.setHorizontalGroup(
            infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacionEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        infoEmpresaLayout.setVerticalGroup(
            infoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoEmpresaLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(panelInformacionEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ventanaPrincipal.addTab("", new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/Home.png")), infoEmpresa, ""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRubrosActionPerformed
        Rubro_Presupuestal rubroPresupuestal = new Rubro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Rubro Presupuestal", rubroPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemRubrosActionPerformed

    private void itemPresupuestoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPresupuestoInicialActionPerformed
        Presupuesto_Inicial presupuesto = new Presupuesto_Inicial(this);
        this.ventanaPrincipal.addTab("Presupuesto", presupuesto);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemPresupuestoInicialActionPerformed

    private void itemAdicionPresupuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdicionPresupuestalActionPerformed
        Adicion_Presupuestal adicion = new Adicion_Presupuestal(this);
        this.ventanaPrincipal.addTab("Adicion Presupuestal", adicion);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemAdicionPresupuestalActionPerformed

    private void itemBeneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBeneficiarioActionPerformed
        Beneficiario_Presupuesto beneficiarioPresupuesto = new Beneficiario_Presupuesto(this);
        this.ventanaPrincipal.addTab("Beneficiario", beneficiarioPresupuesto);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemBeneficiarioActionPerformed

    private void itemDisponibilidadPrespuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDisponibilidadPrespuestalActionPerformed
        Disponibilidad_Presupuestal disponibilidadPresupuestal = new Disponibilidad_Presupuestal(this);
        this.ventanaPrincipal.addTab("Disponibilidad Presupuestal", disponibilidadPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemDisponibilidadPrespuestalActionPerformed

    private void itemEjecucionPrespuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEjecucionPrespuestalActionPerformed
        Ejecucion_Presupuestal ejecucionPresupuestal = new Ejecucion_Presupuestal(this);
        this.ventanaPrincipal.addTab("Ejecución Presupuestal", ejecucionPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemEjecucionPrespuestalActionPerformed

    private void itemTrasladoPresupuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTrasladoPresupuestalActionPerformed
        Traslado_Presupuestal trasladoPresupuestal = new Traslado_Presupuestal(this);
        this.ventanaPrincipal.addTab("Traslado Presupuestal", trasladoPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemTrasladoPresupuestalActionPerformed

    private void itemRegistroPrespuestalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroPrespuestalActionPerformed
        Registro_Presupuestal registroPresupuestal = new Registro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Registro Presupuestal", registroPresupuestal);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemRegistroPrespuestalActionPerformed

    private void itemOrdenPrestacionServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrdenPrestacionServicioActionPerformed
        Orden_Prestacion_Servicio_Presupuestal ops = new Orden_Prestacion_Servicio_Presupuestal(this);
        this.ventanaPrincipal.addTab("Orden de Prestacion de Servicio", ops);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemOrdenPrestacionServicioActionPerformed

    private void itemComprobanteEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComprobanteEgresoActionPerformed
        Comprobante_Egreso comprobante = new Comprobante_Egreso(this);
        this.ventanaPrincipal.addTab("Comrpobante de Egreso", comprobante);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemComprobanteEgresoActionPerformed

    private void itemOrdenSuministroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrdenSuministroActionPerformed
        Orden_Suministro_Presupuestal orden = new Orden_Suministro_Presupuestal(this);
        this.ventanaPrincipal.addTab("Orden de Suministro", orden);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemOrdenSuministroActionPerformed

    private void itemImportarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemImportarDBActionPerformed
        RestaurarBD restaurar = new RestaurarBD(this, true);
        restaurar.setLocationRelativeTo(null);
        restaurar.setVisible(true);
    }//GEN-LAST:event_itemImportarDBActionPerformed

    private void itemExportarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExportarDBActionPerformed
        Backup_BD backup = new Backup_BD(this, true);
        backup.setLocationRelativeTo(null);
        backup.setVisible(true);
    }//GEN-LAST:event_itemExportarDBActionPerformed

    private void itemInformacionEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionEntidadActionPerformed
        Informacion_Entidad entidad = new Informacion_Entidad(this);
        this.ventanaPrincipal.addTab("Informacion de Entidad", entidad);
        this.ventanaPrincipal.setSelectedIndex(this.ventanaPrincipal.getTabCount() - 1);
    }//GEN-LAST:event_itemInformacionEntidadActionPerformed

    private void itemCambioContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCambioContraseñaActionPerformed
        Cambio_Contrasena pass = new Cambio_Contrasena(this, true);
        pass.setLocationRelativeTo(null);
        pass.setVisible(true);
    }//GEN-LAST:event_itemCambioContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    
    //***** Getters & Setters *****//
    
    public JTabbedPane getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(JTabbedPane ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JLabel departamentoCiudad;
    private javax.swing.JInternalFrame infoEmpresa;
    private javax.swing.JMenuItem itemAcercaDe;
    private javax.swing.JMenuItem itemAdicionPresupuestal;
    private javax.swing.JMenu itemBaseDeDatos;
    private javax.swing.JMenuItem itemBeneficiario;
    private javax.swing.JMenuItem itemCambioContraseña;
    private javax.swing.JMenuItem itemComprobanteEgreso;
    private javax.swing.JMenuItem itemDisponibilidadPrespuestal;
    private javax.swing.JMenuItem itemEjecucionPrespuestal;
    private javax.swing.JMenuItem itemExportarDB;
    private javax.swing.JMenuItem itemImportarDB;
    private javax.swing.JMenuItem itemInformacionEntidad;
    private javax.swing.JMenuItem itemOrdenPrestacionServicio;
    private javax.swing.JMenuItem itemOrdenSuministro;
    private javax.swing.JMenuItem itemPresupuestoInicial;
    private javax.swing.JMenuItem itemRegistroPrespuestal;
    private javax.swing.JMenuItem itemRubros;
    private javax.swing.JMenuItem itemTrasladoPresupuestal;
    private javax.swing.JMenu menuAdministrar;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEgresos;
    private javax.swing.JMenu menuPresupuesto;
    private javax.swing.JLabel nitEntidad;
    private javax.swing.JLabel nombreEntidad;
    private javax.swing.JPanel panelInformacionEntidad;
    private javax.swing.JTabbedPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
