/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.presupuesto.vista;

import com.presupuesto.control.AccesoDatos;
import com.presupuesto.modelo.Acceso;
import com.presupuesto.modelo.Entidad;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis Fernando Leiva
 */
public class Login_Dialog extends javax.swing.JDialog implements Runnable {

    public static Home home;
    Thread hilo;
    AccesoDatos accesoDatos;

    /**
     * Creates new form Login
     */
    public Login_Dialog(Home parent, boolean modal) {
        this.home = parent;
        this.setModal(modal);

        initComponents();
        // Icono
        setIconImage(new ImageIcon(getClass().getResource("/com/presupuesto/img/Icono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        frUsuario = new javax.swing.JTextField();
        frPassword = new javax.swing.JPasswordField();
        botonLogin = new javax.swing.JButton();
        labelCerrar = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        labelMensaje = new javax.swing.JLabel();
        iconUsuario = new javax.swing.JLabel();
        iconPass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        frUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frUsuario.setForeground(new java.awt.Color(102, 102, 102));
        frUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        frPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        frPassword.setForeground(new java.awt.Color(102, 102, 102));
        frPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        frPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                frPasswordKeyTyped(evt);
            }
        });

        botonLogin.setBackground(new java.awt.Color(255, 255, 255));
        botonLogin.setForeground(new java.awt.Color(102, 102, 102));
        botonLogin.setText("LOGIN");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        labelCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCerrar.setForeground(new java.awt.Color(102, 102, 102));
        labelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCerrar.setText("X");
        labelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrarMouseClicked(evt);
            }
        });

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/Logo_.png"))); // NOI18N

        labelMensaje.setForeground(new java.awt.Color(153, 0, 0));

        iconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/user.png"))); // NOI18N

        iconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/presupuesto/img/pass.png"))); // NOI18N

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addGap(0, 267, Short.MAX_VALUE)
                        .addComponent(labelCerrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFondoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(labelLogo))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(frPassword)
                            .addComponent(frUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                .addComponent(labelCerrar)
                .addGap(17, 17, 17)
                .addComponent(labelLogo)
                .addGap(37, 37, 37)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(frUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addComponent(iconUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconPass)))
                .addGap(18, 18, 18)
                .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed
        labelMensaje.setText("Validando datos...");
        hilo = new Thread(this);
        hilo.start();
    }//GEN-LAST:event_botonLoginActionPerformed

    private void labelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelCerrarMouseClicked

    private void frPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frPasswordKeyTyped
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            labelMensaje.setText("Validando datos...");
            hilo = new Thread(this);
            hilo.start();
        }
    }//GEN-LAST:event_frPasswordKeyTyped

    private boolean validarLogin() {
        boolean validacionExitosa = false;
        accesoDatos = new AccesoDatos();
        List<Acceso> listaAcceso = new ArrayList<Acceso>();
        Acceso acceso = new Acceso();
        acceso.setUsuario(frUsuario.getText().trim());
        acceso.setPassword(frPassword.getText().trim());

        listaAcceso = accesoDatos.consultarTodos(acceso, Acceso.class);

        if (!listaAcceso.isEmpty()) {
            validacionExitosa = true;
            cargarInformacionEntidad();
            home.setVisible(true);
            this.setVisible(false);
        } else {
            labelMensaje.setText("Usuario y/o Contraseña incorrectos");
        }

        return validacionExitosa;
    }

    private void cargarInformacionEntidad() {
        accesoDatos = new AccesoDatos();
        Entidad entidad = new Entidad();
        List<Entidad> listaEntidad = new ArrayList<Entidad>();

        listaEntidad = accesoDatos.consultarTodos(entidad, Entidad.class);

        entidad = listaEntidad.get(0);

        home.datosEntidad(entidad);
    }

    private void barra() {

//        progressBar.setVisible(true);
//        int num = 0;
//        try {
//            for (int i = num; i < 100; i++) {
//                String Cadena = "";
//                if (i == 50) {
//                    try {
//                        Cadena = "Iniciando conexion BD";
//                        progressBar.setToolTipText(Cadena);
//                        progressBar.setString(Cadena);
//                        Cadena = "Cargando componentes " + i + "%";
//                        //conectar();
//                    } catch (Exception e) {
//                        Cadena = "No existe la base de datos " + i + "%";
//                        progressBar.setToolTipText(Cadena);
//                        progressBar.setString(Cadena);
//                        Cadena = "Base de datos creada " + i + "%";
//                    }
//
//                } else {
//                    Cadena = "Cargando componentes " + i + "%";
//                    Thread.sleep(10);
//                }
//
//                progressBar.setString(Cadena);
//                progressBar.setValue(i);
//            }
//            //abrirVentana();
//
//        } catch (Exception e) {
//            //hilo.interrupt();
//            progressBar.setToolTipText("Error");
//        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login_Dialog dialog = new Login_Dialog(home, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JPasswordField frPassword;
    private javax.swing.JTextField frUsuario;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconUsuario;
    private javax.swing.JLabel labelCerrar;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        validarLogin();
    }
}
